### PR TITLE
#37 is fixed

### PR DESCRIPTION
**Pull request by DmitryDzz**
I've made a fix for #37 bug: After publishing my Android app on Google Play I've got "Supported devices 0" warning. Please, update the dependencies in the message_generation module.

### CODE REVIEW

**Comment by stonier** [comment]
How much testing did you do with messages? Just wondering if the switch from apache -> commons dependencies might cause unforeseen problems.

**Comment by DmitryDzz** [comment]
Hi Daniel, I don't have any special unit tests for this part of project. But there was some kind of integration testing: my project is working. It was tested at least on 3 robots. Each robot has two different Android devices (API Level 15+) with 12 ROS nodes communicating via ROS messages. I can't see any problems with them but the packages are in the Play Market and my friends can simply install them.

**Comment by stonier** [comment]
Ok, patching in. I'll migrate similar to indigo when I revisit the indigo build.

**Comment by stonier** [comment]
Thanks! :neckbeard:

**Comment by DmitryDzz** [comment]
Thanks for sharing your work, Daniel! From my friends, robots and me.

**Pull request merged**
