### PR TITLE
gradle 2.3 + latest jars.

### PR DESCRIPTION
**Pull request by talregev**

### CODE REVIEW

**Comment by talregev** [comment]
don't take that changes. it break the API, and test from rosjava_core will stop pass.

although i am still think it very important to move new API. i just don't know how to do it with out break the other projects. need to understand how to do it.

**Comment by stonier** [comment]
One step at a time, let's get it all working on 2.2 and existing repos for indigo and indigo on windows first. Then experiment :neckbeard:

**Comment by talregev** [comment]
can we talk on gtalk like you suggested? (:

**Comment by stonier** [comment]
Look for me on d.stonier@gmail.com

**Pull request closed without merging**
