### PR TITLE
Update tool versions and add Eclipse support.

### PR DESCRIPTION
**Pull request by damonkohler**

### CODE REVIEW

**Comment by stonier** [comment]
`groovy localGroovy() -> compile localGroovy()` ....... :eyes:

I wonder how that worked previously.

**Comment by stonier** [comment]
Looks good...merging. Should cherrypick this one backwards along with https://github.com/rosjava/rosjava_build_tools/pull/5

**Comment by damonkohler** [comment]
It's just that "groovy" is deprecated and that "compile" is the new hotness.

**Comment by stonier** [comment]
Nothing groovy anymore!? We're losing colour and moving to a monochrome world!

**Pull request merged**
