### PR TITLE
Add Bazel build for message_generation

### PR DESCRIPTION
**Pull request by drigz**
This also allows other Bazel projects (rosjava_core in particular) to
depend on this as an external repository.

It uses https://github.com/johnynek/bazel-deps to describe the Maven
dependencies. As a result, 3rdparty/ contains autogenerated files, and
the other files contain a hand-written description of the BUILD.

Only some of the tests in message_generation have been added. The others
fail at the moment because the .msg resources aren't present.

I will add documentation for the Bazel build to rosjava_core.

### CODE REVIEW

**Comment by drigz** [comment]
@jubeira @damonkohler If you can point me at the gradle configuration that adds the message files to the resources, I can try to do the same for Bazel.

**Comment by jubeira** [comment]
@drigz sorry, I'm not familiar with that Gradle task. 

The message files are already in the `resources` folder; isn't that standard?

**Comment by drigz** [comment]
@jubeira Thanks, that was easier than I thought!

**Review by jubeira — COMMENTED** [review]
I'm not that familiar with Bazel builds, so in this case I trust your judgement.

The only high level comment I have is the version used for the dependencies. Does Bazel use semantic versioning? Perhaps it would be better to use a range of versions as in Gradle buildscripts.

**Comment by drigz** [comment]
Nope, bazel-deps doesn't support version ranges: https://github.com/johnynek/bazel-deps/issues/46

@ensonic Could you review the (non-auto-generated) Bazel files here?

**Review by ensonic — APPROVED** [review]

**Comment by drigz** [comment]
Thank you both!

**Pull request merged**
