### PR TITLE
Generating code for ros action files

### LINKED ISSUE #10: Genjava not processing action messages
Genjava ignores messages generated from action message files. Apparently this has to do with the actionlib message generator putting it's output in [this](https://github.com/ros/common_msgs/blob/jade-devel/actionlib_msgs/cmake/actionlib_msgs-extras.cmake.em#L52) location.

### PR DESCRIPTION
**Pull request by exo-core**
with this changes the message generation also creates files for ROS action files.
This should also resolve [this issue](https://github.com/rosjava/genjava/issues/10).

### CODE REVIEW

**Comment by exo-core** [comment]
I sold my sou... eh, signed it.

**Comment by jubeira** [comment]
Thanks for this wonderful contribution @exo-core!

I took a quick look and codewise it looks good. I'll give it a shot when I have some time and I will approve it if everything goes well.

**Comment by jubeira** [comment]
@exo-core I tried the changes and they seem to work well.

I only have one observation: this will generate the action message artifacts when `add_message_files` + `generate_messages` macros are present in `CMakeLists`; is that right or am I missing something? In other words, you wouldn't need to add `add_action_files` macro to `CMakeLists`.

While I think that it's better to have this than not to have it, this is a small difference wrt. the regular action message generation in `roscpp` and `rospy` that is worth pointing out.

**Comment by exo-core** [comment]
@jubeira you're completely right with your oberservation.

There is a comment in `enjava/src/genjava/templates/genjava_project/build.gradle.in` about the message generator:

```
/* Damon's message generator doesn't catch every message. It expects everything to be nicely under 'msg'
 * and that directory to be under the package root. It also expects every msg it finds should be buildable.
 * It kinda works until now because it ignores any package which doesn't conform to this and those are just
 * test packages (we hope).
```

from what I saw in the code rosjava bootstrap simply crawls the `msg` directory and compiles everything that hast a `*.msg` file type. They same happens for services. Basically all I did was copying the ServiceFileProvider and refactor it to do the same for the `action` directory.

So, yes, the current generator ignores all the `add_message_files`, `add_service_files` and `add_action_files` macros in CMakeLists.txt and just builds everything it finds in the according folders.

Changing the behaviour to be the same as for C++ or Python would probably require to rewrite the whole message discovery procedure.

**Review by jubeira — APPROVED** [review]

**Comment by jubeira** [comment]
Thanks for the changes and the observations @exo-core! PR merged :)

**Pull request merged**
